### ISSUE TITLE
mspgcc is obsclete

### ISSUE THREAD

**Issue by docprofsky** [travisgoodspeed/goodfet#26]
The [mspgcc](https://sourceforge.net/projects/mspgcc/) project is no longer developed and has been superseded by [MSP430-GCC](http://www.ti.com/tool/msp430-gcc-opensource), which is maintained by TI. We should consider moving to that compiler.

**Comment by travisgoodspeed** [comment]
Howdy Schuyler,

Could you send me a pull request to update the documentation for the more modern compiler?

Cheers from Pizza Rat City,
-Travis

**Comment by docprofsky** [comment]
It is a bit more involved than just updating the documentation. There are some changes in the new compiler that require changes to the code and makefile.
You can see the changes I have made so far at [docprofsky/goodfet:new-compiler-support](https://github.com/docprofsky/goodfet/tree/new-compiler-support)

I am getting this error about a missing header, which I think may be from TI changing the headers.
`lib/msp430f2618.c:5:23: fatal error: sys/crtld.h: No such file or directory`

I used these environment variables to point TI GCC at the include directory. In this case `~/opt/ti/gcc` is what I set the install directory to.
`CFLAGS='-I ~/opt/ti/gcc/include/ -L ~/opt/ti/gcc/include/'`

I used this document as a starting point for getting the compiler working.
http://www.ti.com/lit/ug/slau646a/slau646a.pdf

**Comment by finderman2** [comment]
Just wanted to bump this thread to see if any progress has been made. I recently assembled my own goodfet42 from parts, so I need to flash it from a clean source, I installed the TI compiler but can't seem to get the goodfet software to use it

**Comment by travisgoodspeed** [comment]
On Debian/Stretch, the code builds properly with the following packages.  The error concerning `sys/crtld.h` is caused because `msp430-libc` is missing; perhaps it isn't included with TI's toolchain?

```
binutils-msp430 - Binary utilities supporting TI's MSP430 targets
gcc-msp430 - GNU C compiler (cross compiler for MSP430)
gdb-msp430 - The GNU debugger for MSP430
msp430-libc - Standard C library for TI MSP430 development
msp430mcu - Spec files, headers and linker scripts for TI's MSP430 targets
mspdebug - debugging tool for MSP430 microcontrollers
```

**Comment by finderman2** [comment]
I should have mentioned that I was trying this on a mac, I then tried it on an Ubuntu 16 machine (real not VM) and got a different error. It's seems like the goodfet program is timing out trying to send the password, is there anything on the hardware I should check? the TX/RX lights do work and blink, though the RX light doesn’t seem to do anything when the program is sending the password (only TX)

**Comment by docprofsky** [comment]
The issue of programming is probably related to the resetting of the MSP430. I had this issue on MacOS 10.10, thought it probably applies to most versions; I fixed it by installing the FTDI driver.

To build the firmware, I use these packages from MacPorts.
```
msp430-binutils
msp430-gcc
msp430-libc
msp430mcu
```
