### ISSUE TITLE
Facedancer OTG?

### ISSUE THREAD

**Issue by ChaosData** [travisgoodspeed/goodfet#35]
Hi,

Does the facedancer currently (21) support USB OTG? I.e. Is it a dual-role-device that can change its status as a host or device dynamically using SRP/HNP? If so, is switching roles currently supported in the Python stack?

Thanks.

**Comment by travisgoodspeed** [comment]
It supports both host and device modes, but through separate plugs.  The host mode is not very well supported in the code, as most folks use `libusb` for host mode.
