### ISSUE TITLE
Non existing attribute "device_vendor"

### ISSUE THREAD

**Issue by JanMall** [travisgoodspeed/goodfet#40]
An attribute `device_vendor` for object `USBDevice` is used, although it does not exist. So e.g. `USBMassStorage` crashes.

See:
https://github.com/travisgoodspeed/goodfet/blob/master/client/USBDevice.py#L157

**Comment by travisgoodspeed** [comment]
You should probably be using Kate Tempkin's fork of Facedancer, which is available at https://github.com/ktemkin/Facedancer

I'll update the README to mention this, then close the issue.
